import localFont from 'next/font/local';
import './globals.css';
import SessionProvider from './providers/Sessionprovider';

export const metadata = {
  title: 'Mixmatch',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
